; PlatformIO Project Configuration File
; TTGO VGA32 with FabGL

[env:vga32]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
board_build.partitions = partitions.csv
monitor_speed = 115200

lib_deps =
    https://github.com/fdivitto/FabGL.git

build_flags = 
    -Iinclude
    -DCORE_DEBUG_LEVEL=4
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DUMAC_MEMSIZE=1024
    -DDISP_WIDTH=512
    -DDISP_HEIGHT=342
    -DMUSASHI_CNF=\"m68kconf.h\"
    -DENABLE_DASM=0

extra_scripts = pre:add_sources.py
